In [5]:
# KNN Classification Example
# Total training Data = 20 samples
# Total testing Data = 5 samples

import numpy as np
from sklearn.neighbors import KNeighborsClassifier        
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

# Training Dataset
X_train = np.array([
    [2, 50],
    [3, 55],
    [2, 45],
    [4, 60],
    [3, 50],
    [5, 65],
    [6, 70],
    [7, 75],
    [8, 80],
    [6, 78],

    [7, 82],
    [8, 85],
    [9, 88],
    [10, 90],
    [8, 92],
    [9, 95],
    [10, 96],
    [7, 89],
    [8, 84],
    [9, 91]
])

# Labels: 0 = Fail, 1 = Pass
y_train = np.array([
    0, 0, 0, 0, 0,
    0, 0,
    1, 1, 1,
    1, 1, 1, 1, 1,
    1, 1, 1, 1, 1
])
print("Training samples:", len(X_train))          

# Testing Dataset
X_test = np.array([
    [4, 55],
    [6, 72],
    [9, 90],
    [3, 52],
    [8, 88]
])
y_test = np.array([0, 0, 1, 0, 1])
print("Testing samples:", len(X_test))

# Train model
model = KNeighborsClassifier(n_neighbors=3)        
model.fit(X_train, y_train)

# Prediction
prediction = model.predict(X_test)
print("\nPredicted:")                              
print(prediction)
print("\nActual:")
print(y_test)

# Accuracy
acc = accuracy_score(y_test, prediction)
print("\nAccuracy =", acc)

# Confusion Matrix
print("\nConfusion Matrix")
print(confusion_matrix(y_test, prediction))

# Classification Report
print("\nClassification Report")
print(classification_report(y_test, prediction))

Training samples: 20
Testing samples: 5

Predicted:
[0 1 1 0 1]

Actual:
[0 0 1 0 1]

Accuracy = 0.8

Confusion Matrix
[[2 1]
 [0 2]]

Classification Report
              precision    recall  f1-score   support

           0       1.00      0.67      0.80         3
           1       0.67      1.00      0.80         2

    accuracy                           0.80         5
   macro avg       0.83      0.83      0.80         5
weighted avg       0.87      0.80      0.80         5

